### ISSUE TITLE
UnboundLocalError: local variable 'lra_flag' referenced before assignment

### ISSUE THREAD

**Issue by Jane-Gibson** [epi2me-labs/wf-cas9#1]
Hi, 
I'm getting an error trying to run the wf-cas9 workflow via eip2me labs.
I've tried the test data and get the same error, below is output from nextflow.stdout.

Any ideas? Thanks.

```
N E X T F L O W  ~  version 21.10.6
Launching `epi2me-labs/wf-cas9` [furious_curie] - revision: 7750e6b466 [v0.1.2]
NOTE: Your local project version looks outdated - a different revision is available in the remote repository [0733ca442f]
[1mCore Nextflow options[0m
  [0;34mrevision       : [0;32mv0.1.2[0m
  [0;34mrunName        : [0;32mfurious_curie[0m
  [0;34mcontainerEngine: [0;32mdocker[0m
  [0;34mlaunchDir      : [0;32m/mnt/wsl/docker-desktop-bind-mounts/Ubuntu/f393d93e4bb00c72e02ea9258f3b4c2ba61ba4e3b2ab73280ef667df4909b040/epi2melabs-data/nextflow[0m
  [0;34mworkDir        : [0;32m/mnt/wsl/docker-desktop-bind-mounts/Ubuntu/f393d93e4bb00c72e02ea9258f3b4c2ba61ba4e3b2ab73280ef667df4909b040/epi2melabs-data/nextflow/instances/2022-06-28-12-05_wf-cas9_HFnWSWpGfyuVc3sdnYSu7d/work[0m
  [0;34mprojectDir     : [0;32m/home/jg/.nextflow/assets/epi2me-labs/wf-cas9[0m
  [0;34muserName       : [0;32mjg[0m
  [0;34mprofile        : [0;32mstandard[0m
  [0;34mconfigFiles    : [0;32m/home/jg/.nextflow/assets/epi2me-labs/wf-cas9/nextflow.config[0m

[1mBasic Input/Output Options[0m
  [0;34mout_dir        : [0;32mC:\Users\jg\epi2melabs-data\nextflow\instances\2022-06-28-12-05_wf-cas9_HFnWSWpGfyuVc3sdnYSu7d\output[0m
  [0;34mthreads        : [0;32m2[0m
  [0;34mfastq          : [0;32m/mnt/wsl/docker-desktop-bind-mounts/Ubuntu/f393d93e4bb00c72e02ea9258f3b4c2ba61ba4e3b2ab73280ef667df4909b040/Students_and_projects/sample_1_ontarget.fastq.gz[0m
  [0;34mref_genome     : [0;32m/mnt/wsl/docker-desktop-bind-mounts/Ubuntu/f393d93e4bb00c72e02ea9258f3b4c2ba61ba4e3b2ab73280ef667df4909b040/Students_and_projects/grch38_chr19_22.fa.gz[0m
  [0;34mtargets        : [0;32m/mnt/wsl/docker-desktop-bind-mounts/Ubuntu/f393d93e4bb00c72e02ea9258f3b4c2ba61ba4e3b2ab73280ef667df4909b040/Students_and_projects/targets.bed[0m

!! Only displaying parameters that differ from the pipeline defaults !!
-[2m----------------------------------------------------[0m-
If you use wf-template for your analysis please cite:

* The nf-core framework
  https://doi.org/10.1038/s41587-020-0439-x



Checking fastq input.
Single file input detected.
[f8/0b7492] Submitted process > pipeline:getVersions
[c9/4dda0e] Submitted process > pipeline:getParams
[b6/6b96e0] Submitted process > pipeline:build_index
[12/b28bd0] Submitted process > handleSingleFile (1)
[5f/0e32e6] Submitted process > start_ping:pingMessage (1)
[10/f84745] Submitted process > end_ping:pingMessage
[16/f6c567] Submitted process > pipeline:summariseReads (1)
[8e/6de247] Submitted process > pipeline:make_tiles
[bd/9de16e] Submitted process > pipeline:align_reads (1)
Error executing process > 'pipeline:align_reads (1)'

Caused by:
  Process `pipeline:align_reads (1)` terminated with an error exit status (1)

Command executed:

  minimap2 -t 2 -m 4 -ax map-ont genome_index.mmi sample_1_ontarget.fastq > sample_1_ontarget.sam
  bedtools bamtobed -i sample_1_ontarget.sam | bedtools sort > sample_1_ontarget_fastq_pass.bed
  # Get a csv with columns: [read_id, alignment_accuracy]
  stats_from_bam sample_1_ontarget.sam > sample_1_ontarget_aln_stats.csv
  # Add sample id column
  sed "s/$/	sample_1_ontarget/" sample_1_ontarget_aln_stats.csv > tmp
  mv tmp sample_1_ontarget_aln_stats.csv

Command exit status:
  1

Command output:
  (empty)

Command error:
  [M::main::42.956*0.21] loaded/built the index for 2 target sequence(s)
  [M::mm_mapopt_update::43.098*0.21] mid_occ = 220
  [M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 2
  [M::mm_idx_stat::43.183*0.21] distinct minimizers: 10740862 (83.14% are singletons); average occurrences: 1.635; average spacing: 6.232; total length: 109436084
  [M::main] Version: 2.24-r1122
  [M::main] CMD: minimap2 -t 2 -m 4 -ax map-ont genome_index.mmi sample_1_ontarget.fastq
  [M::main] Real time: 43.197 sec; CPU: 9.129 sec; Peak RSS: 0.414 GB
  Traceback (most recent call last):
    File "/home/epi2melabs/conda/bin/stats_from_bam", line 10, in <module>
      sys.exit(main())
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/pomoxis/stats_from_bam.py", line 261, in main
      for batch_counts, results, lra_flag in mapper(func, ranges):
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/pomoxis/stats_from_bam.py", line 219, in _process_reads
      return counts, results, lra_flag
  UnboundLocalError: local variable 'lra_flag' referenced before assignment

Work dir:
  /mnt/wsl/docker-desktop-bind-mounts/Ubuntu/f393d93e4bb00c72e02ea9258f3b4c2ba61ba4e3b2ab73280ef667df4909b040/epi2melabs-data/nextflow/instances/2022-06-28-12-05_wf-cas9_HFnWSWpGfyuVc3sdnYSu7d/work/bd/9de16e7ee7df68021bf7dcef64e21e

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`


WARN: To render the execution DAG in the required format it is required to install Graphviz -- See http://www.graphviz.org for more info.
```

**Comment by nrhorner** [comment]
Hi @Jane-Gibson 

This should be fixed in the latest version (v0.1.3).

**Comment by Jane-Gibson** [comment]
How do I update it? I've done an EPI2ME labs update and an environment update, but its still showing the v0.1.2 workflow version.

**Comment by nrhorner** [comment]
Hi Jane,

Sorry, EPI2ME-labs had not been updated with the latest version of wf-cas9. If you do an environment update now, you should see wf-cas9 v0.15.

**Comment by Jane-Gibson** [comment]
Hi,
The new version gives an error at the pipeline:summariseReads step using fastcat. 
It cannot find the input file:

`Error: could not process file sample_1_ontarget/sample_1_ontarget.fastq.gz: No such file or directory`

This is not the full path I specified.
When I just specify the directory (containing the fastq) rather than the fastq file itself in the fastq box it seems to work fine.


```
N E X T F L O W  ~  version 21.10.6
Launching `epi2me-labs/wf-cas9` [angry_hypatia] - revision: d8aeeb8216 [v0.1.5]
NOTE: Your local project version looks outdated - a different revision is available in the remote repository [f5ad01338b]
[1mCore Nextflow options[0m
  [0;34mrevision       : [0;32mv0.1.5[0m
  [0;34mrunName        : [0;32mangry_hypatia[0m
  [0;34mcontainerEngine: [0;32mdocker[0m
  [0;34mlaunchDir      : [0;32m/mnt/c/Users/jg/epi2melabs-data/nextflow[0m
  [0;34mworkDir        : [0;32m/mnt/c/Users/jg/epi2melabs-data/nextflow/instances/2022-08-15-12-35_wf-cas9_mmkPAiL8J7r45NsymvvZNQ/work[0m
  [0;34mprojectDir     : [0;32m/home/jg/.nextflow/assets/epi2me-labs/wf-cas9[0m
  [0;34muserName       : [0;32mjg[0m
  [0;34mprofile        : [0;32mstandard[0m
  [0;34mconfigFiles    : [0;32m/home/jg/.nextflow/assets/epi2me-labs/wf-cas9/nextflow.config[0m

[1mBasic Input/Output Options[0m
  [0;34mout_dir        : [0;32m/mnt/c/Users/jg/epi2melabs-data/nextflow/instances/2022-08-15-12-35_wf-cas9_mmkPAiL8J7r45NsymvvZNQ/output[0m
  [0;34mthreads        : [0;32m2[0m
  [0;34mfastq          : [0;32m/mnt/c/Users/jg/Documents/Students_and_projects/Marine/sample_1_ontarget.fastq.gz[0m
  [0;34mref_genome     : [0;32m/mnt/c/Users/jg/Documents/Students_and_projects/Marine/grch38_chr19_22.fa.gz[0m
  [0;34mtargets        : [0;32m/mnt/c/Users/jg/Documents/Students_and_projects/Marine/targets.bed[0m

!! Only displaying parameters that differ from the pipeline defaults !!
-[2m----------------------------------------------------[0m-
If you use epi2me-labs/wf-cas9 for your analysis please cite:

* The nf-core framework
  https://doi.org/10.1038/s41587-020-0439-x



Checking fastq input.
Single file input detected.
WARN: Access to undefined parameter `process_label` -- Initialise it to a default value eg. `params.process_label = some_value`
[79/645063] Submitted process > handleSingleFile (1)
[0e/8e26c5] Submitted process > pipeline:getVersions
[56/987b26] Submitted process > pipeline:build_index
[8e/d5e2ba] Submitted process > pipeline:getParams
[8c/b717e8] Submitted process > start_ping:pingMessage (1)
[32/437032] Submitted process > pipeline:summariseReads (1)
[56/b2666d] Submitted process > end_ping:pingMessage
Error executing process > 'pipeline:summariseReads (1)'

Caused by:
  Process `pipeline:summariseReads (1)` terminated with an error exit status (1)

Command executed:

  fastcat -s sample_1_ontarget -r sample_1_ontarget.stats -x sample_1_ontarget > "sample_1_ontarget.fastq"

Command exit status:
  1

Command output:
  (empty)

Command error:
  Processing sample_1_ontarget/sample_1_ontarget.fastq.gz
  Error: could not process file sample_1_ontarget/sample_1_ontarget.fastq.gz: No such file or directory
  Completed processing with errors. Outputs may be incomplete.

Work dir:
  /mnt/c/Users/jg/epi2melabs-data/nextflow/instances/2022-08-15-12-35_wf-cas9_mmkPAiL8J7r45NsymvvZNQ/work/32/4370322e5008aff4a1a914ec713c5c

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`


WARN: Killing pending tasks (3)
```

**Comment by nrhorner** [comment]
Hi @Jane-Gibson,

I do apologise about this. I'm looking into it now.

**Comment by nrhorner** [comment]
Hi Jane. I just realised I never got back to you about this. I'm be interested to know if this issue is fixed in the latest releas (v0.1.11)

**Comment by nrhorner** [comment]
Closing due to lack of response
